spec:
  template:
    spec:
      volumes:
        - configMap:
            # Name of the config map
            name: amqp-test-receiver-config
            optional: true
            # Define the items from the config map to mount
            items:
            - key: application.properties
              path: application.properties
            # Volume name (used as reference below)
          name: config
      containers:
        - name: amqp-test-receiver
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_OPTIONS
              value: '-Dvertx.cacheDirBase=/tmp -Dvertx.jgroups.config=default'
            - name: VERTX_CONFIG_PATH
              value: '/deployments/config/application.properties'
          volumeMounts: 
            - name: config 
              mountPath: /deployments/config